// Generado por web_i18n/i18n_rebuild.js (fr) a partir de web/js/maps.js. No editar a mano: editar la memoria tm/fr.json y regenerar.
const MAPS = {
 "map-fil-que-es": {
  "subject": "fil",
  "tema": "Philosophie · Thème 1",
  "title": "Qu'est-ce que la philosophie ?",
  "md": "# Qu'est-ce que la philosophie ?\n## Amour de la sagesse\n- *Philía* (amour) + *sophía* (sagesse)\n- Le philosophe **cherche** la vérité, il ne la possède pas\n- Elle naît de l'**étonnement**, de la curiosité et du doute\n- « Je sais seulement que je ne sais rien » (**Socrate**)\n## Du mythe au logos\n- Grèce, **VIe s. av. J.-C.**\n- **Mythe** : récit de dieux ; anthropomorphique, arbitraire, **dogmatique**\n- **Logos** : causes naturelles et **arguments** ; **critique**\n- **Thalès de Milet** cherche l'**arkhé**\n## Les types de savoir\n- **Commun** : spontané, non réflexif\n- **Scientifique** : causes prochaines ; **partiel**\n- **Philosophique** : causes ultimes ; la réalité **dans son ensemble**\n## Caractères du savoir philosophique\n- **Rationnel** et **critique**\n- **Radical** : il va à la racine\n- **Universel** et **systématique**\n- **Pratique** : éthique et politique\n- **Ouvert** et **historique**\n## Les branches\n- **Métaphysique** : qu'est-ce qu'être, qu'est-ce qui existe\n- **Théorie de la connaissance** : que pouvons-nous connaître\n- **Éthique** et **philosophie politique**\n- **Esthétique**, **logique** et **anthropologie**\n## Avec les autres savoirs\n- **Science** : données et expériences\n- **Religion** : foi et révélation\n- **Art** : œuvres qui font ressentir\n- **Philosophie** : concepts et arguments\n## À quoi elle sert\n- Penser par soi-même\n- Lire et commenter des **textes**"
 },
 "map-filosofia-ciencia": {
  "subject": "fil",
  "tema": "Philosophie · Philosophie des sciences",
  "title": "Philosophie des sciences",
  "md": "# Philosophie des sciences\n## Questions centrales\n- Qu'est-ce que la **connaissance scientifique** ?\n- Comment s'obtient-elle ?\n- Qu'est-ce qui distingue la science des autres savoirs ?\n## Philosophie de la physique\n- **Espace et temps** — Newton contre Leibniz ; relativité ; quantique\n- **Causalité** — déterminisme contre indéterminisme\n## Épistémologie scientifique\n- **Réalisme** — les théories décrivent la vérité\n- **Instrumentalisme** — les théories sont des outils\n- **Construction sociale** de la connaissance\n- Preuve : **induction**, **falsification** (Popper), théorème de Bayes\n## Méthodologie\n- **Méthode scientifique** — observation, hypothèse, expérimentation, théorie\n- Classification : sciences formelles, physiques, biologiques et sociales\n## Philosophie des mathématiques\n- **Platonisme** — les objets mathématiques existent\n- **Nominalisme** — ils ne sont que du langage\n- **Intuitionnisme** — ils sont une construction humaine\n## Histoire des sciences\n- Révolutions : **Copernic**, **Newton**, **Einstein**, quantique\n- **Galilée** — début de la révolution scientifique"
 },
 "map-ser-humano": {
  "subject": "fil",
  "tema": "Philosophie · Thème 2",
  "title": "Qu'est-ce que l'être humain ?",
  "md": "# Qu'est-ce que l'être humain ?\n## Nature et culture\n- **Évolution** → **hominisation** (biologique)\n- **Culture** → **humanisation** (apprise)\n- Dialectique nature-culture ; nous naissons « inachevés »\n## Culture, identité et diversité\n- **Socialisation** ; identité personnelle et collective\n- **Ethnocentrisme / relativisme / interculturalité**\n## Corps et esprit\n- **Dualisme** — Platon (prison de l'âme) ; Descartes (res cogitans / res extensa)\n- **Monisme / matérialisme** — nous sommes corps\n- Aristote — l'âme, **forme** du corps\n## Conceptions au fil de l'histoire\n- Antiquité — animal **rationnel** et social\n- Moyen Âge — créature à l'image de Dieu\n- Modernité — sujet qui pense (Descartes) ; **dignité** (Kant)\n- Époque contemporaine — Marx (travail), Nietzsche, existentialisme (**projet** et liberté)\n## Conscience, langage et personne\n- **Conscience** et conscience de soi (introspection)\n- **Langage** symbolique\n- **Personne** — dignité ; fin en soi\n## Identité personnelle\n- Bateau de Thésée ; **mémoire** (Locke) ; Hume ; le récit\n- **Transhumanisme**\n## Le sens de l'existence\n- Absurde / transcendant / immanent / **se donner soi-même un sens**"
 },
 "map-conocimiento": {
  "subject": "fil",
  "tema": "Philosophie · Thème 3",
  "title": "Que pouvons-nous connaître ?",
  "md": "# Que pouvons-nous connaître ?\n## La connaissance humaine\n- Relation **sujet — objet**\n- Degrés : **sensation → perception → concept** (abstraction)\n- La branche : **épistémologie / gnoséologie**\n## Les sources de la connaissance\n- **Rationalisme** (Descartes) — la raison ; idées innées\n- **Empirisme** (Locke, Hume) — l'expérience ; *tabula rasa*\n- **Criticisme** (Kant) — expérience + raison\n## Pouvons-nous atteindre la vérité ?\n- **Dogmatisme** · **Scepticisme** · **Relativisme** · **Criticisme**\n## La question de la vérité\n- Opinion (**doxa**) face à science (**épistémè**)\n- Théories : **correspondance**, cohérence, consensus, pragmatique\n## La post-vérité\n- Les faits pèsent moins que les émotions\n- Infox, **fake news**, biais, bulles d'écho\n- Défense : **esprit critique** et recoupement des sources\n## Le savoir scientifique\n- Sciences **formelles** et **empiriques** (naturelles / sociales)\n- **Méthode hypothético-déductive** ; Popper (falsifiabilité), Kuhn (paradigmes)\n## Science, technologie et art\n- Science / technique / **technologie** ; limites éthiques\n- La **femme dans la science**"
 },
 "map-racionalismo-empirismo": {
  "subject": "fil",
  "tema": "Philosophie · Rationalisme et empirisme",
  "title": "Rationalisme contre empirisme",
  "md": "# Rationalisme contre empirisme\n## Le problème\n- Époque moderne : quel est le **fondement de la connaissance** ?\n## Rationalisme\n- Représentant : **Descartes**\n- Source : la **raison** — connaissance **a priori**\n- **Idées innées** : Dieu (res infinita), res cogitans, res extensa\n- **Dogmatisme** : il ne doute pas de la capacité de la raison\n- Vérités **universelles et nécessaires**\n- Méthode **déductive** ; modèle : les **mathématiques**\n## Empirisme\n- Représentants : **Locke** et **Hume**\n- Source : l'**expérience** — connaissance **a posteriori**\n- Locke — l'esprit à la naissance est une **tabula rasa**\n- Hume — il doute de la **causalité** (habitude) → **scepticisme**\n- Vérités générales et **provisoires**\n- Méthode **inductive** ; modèle : la **science expérimentale**\n## Synthèse : Kant\n- Le **criticisme** unit raison et expérience\n- Il redéfinit philosophie, métaphysique et science"
 },
 "map-fil-mito-logos": {
  "subject": "fil",
  "tema": "Philosophie · Thème 1",
  "title": "Du mythe au logos",
  "md": "# Du mythe au logos\n## Le passage décisif\n- Grèce, **VIe s. av. J.-C.** : naissance de la philosophie\n- D'expliquer par des **dieux** à expliquer par des **raisons**\n## Mythe (mythos)\n- Récits de **dieux** à la volonté capricieuse\n- **Anthropomorphique et animiste**\n- Transmis par tradition orale\n- **Dogmatique** : on l'accepte sans discuter\n## Logos (raison)\n- Cherche des **causes naturelles** et des lois\n- S'appuie sur des **arguments** ; a un auteur\n- **Critique** : on peut le discuter et le réviser\n## Les premiers philosophes\n- Ils cherchent l'**arkhé** (le principe de toute chose)\n- **Thalès de Milet** : l'eau\n- L'essentiel : le **changement de méthode**"
 },
 "map-fil-logica": {
  "subject": "fil",
  "tema": "Philosophie · Thème 4",
  "title": "Logique et argumentation",
  "md": "# Logique et argumentation\n## Ce qu'étudie la logique\n- La **correction** des raisonnements\n- La **forme** de la pensée, non son contenu\n- Elle fut fondée par **Aristote** (théorie du **syllogisme**)\n## Propositions et arguments\n- **Proposition** : énoncé vrai ou faux\n- **Argument** : des **prémisses** qui soutiennent une **conclusion**\n- Argumenter, c'est **donner des raisons**\n## Modes de raisonnement\n- **Déduction** : conclusion **nécessaire**\n- **Induction** : des cas au général ; seulement **probable**\n- **Abduction** : la **meilleure explication** (Peirce)\n- **Analogie** : ressemblances pertinentes ; risque de **fausse analogie**\n## Validité et vérité\n- **Validité** : propriété de la **forme**\n- **Vérité** : propriété du **contenu**\n- **Solide** = valide + prémisses vraies\n- Une induction n'est pas valide ou invalide, mais **forte** ou **faible**\n## Logique formelle et symbolique\n- **Frege** : logique du premier ordre\n- **Connecteurs** et **tables de vérité** ; **tautologie** et **contradiction**\n- **Boole** et **Shannon** : de la logique aux **portes logiques**\n- Le **paradoxe** du menteur\n## Les sophismes\n- Ils semblent valides, mais ne le sont pas\n- **Formels** (la forme) et **informels** (le contenu ou le langage)\n- *Ad hominem*, *ad populum*, homme de paille, fausse cause…\n- **Sophisme** (à dessein) et **paralogisme** (sans le vouloir)\n## Analyser et dialoguer\n- Indicateurs ; **prémisses implicites** (**enthymème**)\n- **Charge de la preuve** et **principe de charité**\n- **Contre-exemple** et **réduction à l'absurde**\n- Raisonner, non **rationaliser**\n## Définir et distinguer\n- **Genre prochain** + **différence spécifique**\n- Condition **nécessaire** et **suffisante**\n- **Analyse conceptuelle** : qu'est-ce que mentir ?"
 },
 "map-fil-etica": {
  "subject": "fil",
  "tema": "Philosophie · Thème 5",
  "title": "Les questions de l'éthique",
  "md": "# Les questions de l'éthique\n## Éthique et morale\n- **Morale** : normes et valeurs qui régissent une communauté\n- **Éthique** : réflexion philosophique sur la morale\n- « Comment devons-nous vivre ? » (**Socrate**)\n- Niveaux : éthique **normative**, **appliquée** et **métaéthique**\n## La liberté, condition de la morale\n- Sans liberté, pas de **responsabilité**\n- **Autonomie** face à **hétéronomie** (Kant)\n- **Incompatibilisme** et **compatibilisme**\n## Éthiques matérielles\n- Elles disent quel est le **bien** ou la fin : **téléologiques**\n- **Aristote** : *eudaimonía* ; la vertu comme **juste milieu**\n- **Épicure** : le plaisir comme *ataraxie*\n- **Utilitarisme** (Bentham, Mill) : « le plus grand bonheur du plus grand nombre »\n## L'éthique formelle de Kant\n- **Déontologique** : agir **par devoir**\n- **Impératif catégorique** : une maxime qui puisse devenir **loi universelle**\n- L'humanité, toujours comme **fin** et jamais simplement comme moyen\n## Y a-t-il des vérités morales ?\n- **Objectivisme** : des faits moraux valables pour tous\n- **Subjectivisme** et **relativisme culturel**\n- **Non-cognitivisme** : l'**émotivisme** (Hume, Ayer)\n- Sans critique possible, pas de **progrès moral**\n## Le jugement moral\n- **Piaget** : de la morale **hétéronome** à la morale **autonome**\n- **Kohlberg** : trois niveaux ; le **dilemme de Heinz**\n- **Gilligan** : la voix du **care**\n## Soupçon et cas limites\n- **Nietzsche** : morale des **maîtres** et des **esclaves** ; **transvaluation**\n- L'utilitarisme mis à l'épreuve : le **tramway** et la greffe\n- **Singer** : exige-t-il trop ?\n## Éthique appliquée aujourd'hui\n- **Éthique du care** (Noddings, Tronto)\n- **Bioéthique** : autonomie, bienfaisance, non-malfaisance et justice\n- Éthique **animale** (**spécisme**) et éthique de l'**IA**"
 },
 "map-fil-politica": {
  "subject": "fil",
  "tema": "Philosophie · Thème 6",
  "title": "La vie en société",
  "md": "# La vie en société\n## Un animal politique\n- **Aristote** : *zoon politikón*\n- Celui qui vit isolé « est ou une bête ou un dieu »\n- La philosophie politique demande comment les sociétés **devraient** être\n## Pourquoi l'État existe-t-il ?\n- Anciens : la communauté politique est **naturelle**\n- Modernes : un artifice, le **contrat social**\n- L'**état de nature** : une hypothèse, non un fait\n- Critiques : **Hume** (conquête et utilité) et **Kant** (idée de la raison)\n## Les contractualistes\n- **Hobbes** : guerre de tous contre tous → le **Léviathan**\n- **Locke** : droits naturels → **État libéral** et droit de résistance\n- **Rousseau** : **volonté générale** → **souveraineté populaire**\n## Pouvoir et légitimité\n- **Pouvoir** : faire obéir les autres\n- **Légitimité** : le droit de commander\n- **Weber** : tradition, charisme et **légalité rationnelle**\n## La justice\n- **Distributive** et **corrective** (Aristote)\n- **Rawls** : **voile d'ignorance** et **principe de différence**\n- **Nozick** : la titularité et l'**État minimal**\n- **Communautarisme** (Sandel) : les biens que nous partageons\n## Formes de gouvernement\n- Un, quelques-uns, beaucoup : **monarchie**, **aristocratie**, **politeia**\n- Dégénérées, dans l'intérêt propre : **tyrannie**, **oligarchie** et, pour Aristote, **démocratie**\n- Démocratie moderne : **libérale**, **délibérative**, **participative**\n- Menaces : **tyrannie de la majorité**, **populisme**, érosion de l'intérieur\n## Droits et liberté\n- **Droits de l'homme** (1948) : trois **générations**\n- **État de droit** face au **totalitarisme** (Arendt)\n- **Berlin** : liberté **négative** et liberté **positive**\n## Imaginer et élargir le pacte\n- **Utopies** (Platon, More) et **dystopies** (Huxley, Orwell)\n- **Féminisme** : patriarcat, **sexe et genre**, intersectionnalité\n- « On ne naît pas femme : on le devient » (**Beauvoir**)"
 },
 "map-fil-estetica": {
  "subject": "fil",
  "tema": "Philosophie · Thème 7",
  "title": "Qu'est-ce que l'art ?",
  "md": "# Qu'est-ce que l'art ?\n## L'esthétique\n- Elle réfléchit sur la **beauté**, l'**art** et l'**expérience esthétique**\n- Du grec *aísthesis* : sensation (**Baumgarten**)\n- Contempler quelque chose **pour lui-même**, sans chercher son utilité\n## Où est la beauté ?\n- **Objective** (classique) : proportion, harmonie, ordre et mesure\n- Pythagoriciens, **Polyclète** (*Canon*), Augustin, Thomas\n- **Subjective** (moderne) : le plaisir de celui qui regarde\n- Autres catégories : **le sublime**, le laid, le tragique, le comique\n## Le jugement de goût\n- **Hume** : le **critique compétent**\n- **Kant** : **désintéressé** et **universel sans concept**\n- **Finalité sans fin** ; beauté **libre** et **adhérente**\n## Théories de l'art\n- **Imitation** (*mímesis*) : représenter la réalité\n- **Expression** (Romantisme) : l'émotion de l'auteur\n- **Forme** (formalisme) : composition, couleur, rythme\n- **Institutionnelle** (Danto, Dickie) : ce que reconnaît le monde de l'art\n## Art et vérité\n- **Platon** : copie d'une copie ; l'art **trompe**\n- **Aristote** : *mímesis* et **catharsis**\n- **Hegel** : la « **fin de l'art** »\n- **Heidegger** et **Gadamer** : l'œuvre ouvre un monde\n## Art, émotion et morale\n- L'art **éduque** les sentiments\n- **Schiller** : le **jeu** et l'éducation esthétique\n- **Moralisme** face à **autonomisme** (« l'art pour l'art »)\n## Art et politique\n- **Art engagé** face à **art pour l'art**\n- **Benjamin** : le fascisme **esthétise la politique**\n- **Adorno** : l'**industrie culturelle**\n## L'image aujourd'hui\n- **Duchamp** et le **ready-made**\n- **Benjamin** : reproductibilité technique et perte de l'**aura**\n- **Debord** (spectacle) et **Baudrillard** (**simulacre**)\n- **Alphabétisation visuelle** : regarder avec un esprit critique"
 },
 "map-fil-metafisica": {
  "subject": "fil",
  "tema": "Philosophie · M",
  "title": "La réalité : qu'y a-t-il et comment est-elle ?",
  "md": "# La réalité : qu'y a-t-il et comment est-elle ?\n## La métaphysique\n- Elle demande **ce qui existe** et comment c'est en dernière instance\n- *Ta meta ta physika* ; la « **philosophie première** » d'Aristote\n- **Ontologie** : quels types de choses existent\n- Critiques : **Kant** et le **Cercle de Vienne**\n## Apparence et réalité\n- **Parménide** : l'être est un et immuable ; le changement, apparence\n- **Platon** : monde **sensible** et monde des **Idées**\n- **Bostrom** : l'argument de la **simulation**\n## De quoi tout est-il fait ?\n- **Monisme** (Spinoza), **dualisme** (Descartes), **pluralisme** (Empédocle, Leibniz)\n- **Matérialisme** : tout est matière (Démocrite, Hobbes, le physicalisme)\n- **Idéalisme** : « être, c'est être perçu » (**Berkeley**)\n## Substance, essence et existence\n- **Aristote** : la **substance** et ses **accidents**\n- **Hylémorphisme** : **matière** + **forme**\n- **Acte** et **puissance** : ainsi s'explique le changement\n- **Sartre** : « l'existence précède l'essence »\n## Esprit, corps et IA\n- **Dualisme** : comment interagissent-ils ? (Élisabeth de Bohême)\n- **Théorie de l'identité** : états du cerveau\n- **Fonctionnalisme** (Putnam) : l'esprit se définit par sa fonction\n- Le **test de Turing** face à la **chambre chinoise** (Searle)\n- Le **problème difficile** de la conscience (Chalmers)\n## Le temps et le changement\n- **Héraclite** : tout change (le fleuve)\n- **Zénon** : Achille et la tortue\n- Le **bateau de Thésée** (Plutarque) : est-il toujours le même ?\n- **Newton** (temps absolu) face à **Leibniz** (relatif) ; **Einstein**\n- **Présentisme** et **éternalisme**\n## Sommes-nous libres ?\n- **Déterminisme** (le démon de Laplace) et **indéterminisme**\n- **Déterminisme dur** : la liberté est une illusion\n- **Libertarisme** : nous aurions pu agir autrement\n- **Compatibilisme** : être libre, c'est agir sans **contrainte**\n## Dieu existe-t-il ?\n- Argument **ontologique** (Anselme)\n- Argument **cosmologique** (les cinq voies) et du **dessein** (Paley)\n- Contre : le **problème du mal** ; réponse : la **théodicée**\n- Cas à part : le **pari de Pascal**\n- **Théisme**, **athéisme**, **agnosticisme** et **fidéisme**"
 },
 "map-fil-cuerpo-mente": {
  "subject": "fil",
  "tema": "Philosophie · Thème 2",
  "title": "Le corps et l'esprit",
  "md": "# Le corps et l'esprit\n## Le problème corps-esprit\n- Sommes-nous **une** chose ou **deux** ?\n## Dualisme (deux réalités)\n- Corps **matériel** + âme **immatérielle** (l'essentiel)\n- **Platon** — âme immortelle, corps « prison » ; char ailé ; âme en 3 parties (rationnelle, irascible, concupiscible)\n- **Descartes** — res cogitans (esprit) contre res extensa (corps-machine)\n## Monisme matérialiste (une réalité)\n- Il n'y a que le **corps** ; l'esprit est son **activité** (le cerveau)\n- **Démocrite**, **Hobbes**, **La Mettrie** (l'homme machine) ; aujourd'hui, **Dennett** et les **Churchland**\n## Les problèmes\n- Dualisme : comment l'esprit et le corps communiquent-ils ?\n- Monisme : sommes-nous **libres** ou seulement chimie ?"
 }
};
